#ifndef INCLUDED_CYFITTER_H
#define INCLUDED_CYFITTER_H
#include "cydevice_trm.h"

/* EZI2C_SCB */
#define EZI2C_SCB__CTRL CYREG_SCB0_CTRL
#define EZI2C_SCB__EZ_DATA0 CYREG_SCB0_EZ_DATA0
#define EZI2C_SCB__EZ_DATA1 CYREG_SCB0_EZ_DATA1
#define EZI2C_SCB__EZ_DATA10 CYREG_SCB0_EZ_DATA10
#define EZI2C_SCB__EZ_DATA11 CYREG_SCB0_EZ_DATA11
#define EZI2C_SCB__EZ_DATA12 CYREG_SCB0_EZ_DATA12
#define EZI2C_SCB__EZ_DATA13 CYREG_SCB0_EZ_DATA13
#define EZI2C_SCB__EZ_DATA14 CYREG_SCB0_EZ_DATA14
#define EZI2C_SCB__EZ_DATA15 CYREG_SCB0_EZ_DATA15
#define EZI2C_SCB__EZ_DATA16 CYREG_SCB0_EZ_DATA16
#define EZI2C_SCB__EZ_DATA17 CYREG_SCB0_EZ_DATA17
#define EZI2C_SCB__EZ_DATA18 CYREG_SCB0_EZ_DATA18
#define EZI2C_SCB__EZ_DATA19 CYREG_SCB0_EZ_DATA19
#define EZI2C_SCB__EZ_DATA2 CYREG_SCB0_EZ_DATA2
#define EZI2C_SCB__EZ_DATA20 CYREG_SCB0_EZ_DATA20
#define EZI2C_SCB__EZ_DATA21 CYREG_SCB0_EZ_DATA21
#define EZI2C_SCB__EZ_DATA22 CYREG_SCB0_EZ_DATA22
#define EZI2C_SCB__EZ_DATA23 CYREG_SCB0_EZ_DATA23
#define EZI2C_SCB__EZ_DATA24 CYREG_SCB0_EZ_DATA24
#define EZI2C_SCB__EZ_DATA25 CYREG_SCB0_EZ_DATA25
#define EZI2C_SCB__EZ_DATA26 CYREG_SCB0_EZ_DATA26
#define EZI2C_SCB__EZ_DATA27 CYREG_SCB0_EZ_DATA27
#define EZI2C_SCB__EZ_DATA28 CYREG_SCB0_EZ_DATA28
#define EZI2C_SCB__EZ_DATA29 CYREG_SCB0_EZ_DATA29
#define EZI2C_SCB__EZ_DATA3 CYREG_SCB0_EZ_DATA3
#define EZI2C_SCB__EZ_DATA30 CYREG_SCB0_EZ_DATA30
#define EZI2C_SCB__EZ_DATA31 CYREG_SCB0_EZ_DATA31
#define EZI2C_SCB__EZ_DATA4 CYREG_SCB0_EZ_DATA4
#define EZI2C_SCB__EZ_DATA5 CYREG_SCB0_EZ_DATA5
#define EZI2C_SCB__EZ_DATA6 CYREG_SCB0_EZ_DATA6
#define EZI2C_SCB__EZ_DATA7 CYREG_SCB0_EZ_DATA7
#define EZI2C_SCB__EZ_DATA8 CYREG_SCB0_EZ_DATA8
#define EZI2C_SCB__EZ_DATA9 CYREG_SCB0_EZ_DATA9
#define EZI2C_SCB__I2C_CFG CYREG_SCB0_I2C_CFG
#define EZI2C_SCB__I2C_CTRL CYREG_SCB0_I2C_CTRL
#define EZI2C_SCB__I2C_M_CMD CYREG_SCB0_I2C_M_CMD
#define EZI2C_SCB__I2C_S_CMD CYREG_SCB0_I2C_S_CMD
#define EZI2C_SCB__I2C_STATUS CYREG_SCB0_I2C_STATUS
#define EZI2C_SCB__INTR_CAUSE CYREG_SCB0_INTR_CAUSE
#define EZI2C_SCB__INTR_I2C_EC CYREG_SCB0_INTR_I2C_EC
#define EZI2C_SCB__INTR_I2C_EC_MASK CYREG_SCB0_INTR_I2C_EC_MASK
#define EZI2C_SCB__INTR_I2C_EC_MASKED CYREG_SCB0_INTR_I2C_EC_MASKED
#define EZI2C_SCB__INTR_M CYREG_SCB0_INTR_M
#define EZI2C_SCB__INTR_M_MASK CYREG_SCB0_INTR_M_MASK
#define EZI2C_SCB__INTR_M_MASKED CYREG_SCB0_INTR_M_MASKED
#define EZI2C_SCB__INTR_M_SET CYREG_SCB0_INTR_M_SET
#define EZI2C_SCB__INTR_RX CYREG_SCB0_INTR_RX
#define EZI2C_SCB__INTR_RX_MASK CYREG_SCB0_INTR_RX_MASK
#define EZI2C_SCB__INTR_RX_MASKED CYREG_SCB0_INTR_RX_MASKED
#define EZI2C_SCB__INTR_RX_SET CYREG_SCB0_INTR_RX_SET
#define EZI2C_SCB__INTR_S CYREG_SCB0_INTR_S
#define EZI2C_SCB__INTR_S_MASK CYREG_SCB0_INTR_S_MASK
#define EZI2C_SCB__INTR_S_MASKED CYREG_SCB0_INTR_S_MASKED
#define EZI2C_SCB__INTR_S_SET CYREG_SCB0_INTR_S_SET
#define EZI2C_SCB__INTR_SPI_EC CYREG_SCB0_INTR_SPI_EC
#define EZI2C_SCB__INTR_SPI_EC_MASK CYREG_SCB0_INTR_SPI_EC_MASK
#define EZI2C_SCB__INTR_SPI_EC_MASKED CYREG_SCB0_INTR_SPI_EC_MASKED
#define EZI2C_SCB__INTR_TX CYREG_SCB0_INTR_TX
#define EZI2C_SCB__INTR_TX_MASK CYREG_SCB0_INTR_TX_MASK
#define EZI2C_SCB__INTR_TX_MASKED CYREG_SCB0_INTR_TX_MASKED
#define EZI2C_SCB__INTR_TX_SET CYREG_SCB0_INTR_TX_SET
#define EZI2C_SCB__RX_CTRL CYREG_SCB0_RX_CTRL
#define EZI2C_SCB__RX_FIFO_CTRL CYREG_SCB0_RX_FIFO_CTRL
#define EZI2C_SCB__RX_FIFO_RD CYREG_SCB0_RX_FIFO_RD
#define EZI2C_SCB__RX_FIFO_RD_SILENT CYREG_SCB0_RX_FIFO_RD_SILENT
#define EZI2C_SCB__RX_FIFO_STATUS CYREG_SCB0_RX_FIFO_STATUS
#define EZI2C_SCB__RX_MATCH CYREG_SCB0_RX_MATCH
#define EZI2C_SCB__SPI_CTRL CYREG_SCB0_SPI_CTRL
#define EZI2C_SCB__SPI_STATUS CYREG_SCB0_SPI_STATUS
#define EZI2C_SCB__SS0_POSISTION 0u
#define EZI2C_SCB__SS1_POSISTION 1u
#define EZI2C_SCB__SS2_POSISTION 2u
#define EZI2C_SCB__SS3_POSISTION 3u
#define EZI2C_SCB__STATUS CYREG_SCB0_STATUS
#define EZI2C_SCB__TX_CTRL CYREG_SCB0_TX_CTRL
#define EZI2C_SCB__TX_FIFO_CTRL CYREG_SCB0_TX_FIFO_CTRL
#define EZI2C_SCB__TX_FIFO_STATUS CYREG_SCB0_TX_FIFO_STATUS
#define EZI2C_SCB__TX_FIFO_WR CYREG_SCB0_TX_FIFO_WR
#define EZI2C_SCB__UART_CTRL CYREG_SCB0_UART_CTRL
#define EZI2C_SCB__UART_FLOW_CTRL CYREG_SCB0_UART_FLOW_CTRL
#define EZI2C_SCB__UART_RX_CTRL CYREG_SCB0_UART_RX_CTRL
#define EZI2C_SCB__UART_RX_STATUS CYREG_SCB0_UART_RX_STATUS
#define EZI2C_SCB__UART_TX_CTRL CYREG_SCB0_UART_TX_CTRL

/* EZI2C_SCB_IRQ */
#define EZI2C_SCB_IRQ__INTC_CLR_EN_REG CYREG_CM0P_ICER
#define EZI2C_SCB_IRQ__INTC_CLR_PD_REG CYREG_CM0P_ICPR
#define EZI2C_SCB_IRQ__INTC_MASK 0x80u
#define EZI2C_SCB_IRQ__INTC_NUMBER 7u
#define EZI2C_SCB_IRQ__INTC_PRIOR_MASK 0xC0000000u
#define EZI2C_SCB_IRQ__INTC_PRIOR_NUM 2u
#define EZI2C_SCB_IRQ__INTC_PRIOR_REG CYREG_CM0P_IPR1
#define EZI2C_SCB_IRQ__INTC_SET_EN_REG CYREG_CM0P_ISER
#define EZI2C_SCB_IRQ__INTC_SET_PD_REG CYREG_CM0P_ISPR

/* EZI2C_SCBCLK */
#define EZI2C_SCBCLK__CTRL_REGISTER CYREG_PERI_PCLK_CTL0
#define EZI2C_SCBCLK__DIV_ID 0x00000041u
#define EZI2C_SCBCLK__DIV_REGISTER CYREG_PERI_DIV_16_CTL1
#define EZI2C_SCBCLK__PA_DIV_ID 0x000000FFu

/* EZI2C_scl */
#define EZI2C_scl__0__DR CYREG_GPIO_PRT1_DR
#define EZI2C_scl__0__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define EZI2C_scl__0__DR_INV CYREG_GPIO_PRT1_DR_INV
#define EZI2C_scl__0__DR_SET CYREG_GPIO_PRT1_DR_SET
#define EZI2C_scl__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define EZI2C_scl__0__HSIOM_GPIO 0u
#define EZI2C_scl__0__HSIOM_I2C 14u
#define EZI2C_scl__0__HSIOM_I2C_SCL 14u
#define EZI2C_scl__0__HSIOM_MASK 0x0000000Fu
#define EZI2C_scl__0__HSIOM_SHIFT 0u
#define EZI2C_scl__0__HSIOM_SPI 15u
#define EZI2C_scl__0__HSIOM_SPI_MOSI 15u
#define EZI2C_scl__0__HSIOM_UART 9u
#define EZI2C_scl__0__HSIOM_UART_RX 9u
#define EZI2C_scl__0__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define EZI2C_scl__0__INTR CYREG_GPIO_PRT1_INTR
#define EZI2C_scl__0__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define EZI2C_scl__0__INTSTAT CYREG_GPIO_PRT1_INTR
#define EZI2C_scl__0__MASK 0x01u
#define EZI2C_scl__0__PC CYREG_GPIO_PRT1_PC
#define EZI2C_scl__0__PC2 CYREG_GPIO_PRT1_PC2
#define EZI2C_scl__0__PORT 1u
#define EZI2C_scl__0__PS CYREG_GPIO_PRT1_PS
#define EZI2C_scl__0__SHIFT 0u
#define EZI2C_scl__DR CYREG_GPIO_PRT1_DR
#define EZI2C_scl__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define EZI2C_scl__DR_INV CYREG_GPIO_PRT1_DR_INV
#define EZI2C_scl__DR_SET CYREG_GPIO_PRT1_DR_SET
#define EZI2C_scl__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define EZI2C_scl__INTR CYREG_GPIO_PRT1_INTR
#define EZI2C_scl__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define EZI2C_scl__INTSTAT CYREG_GPIO_PRT1_INTR
#define EZI2C_scl__MASK 0x01u
#define EZI2C_scl__PC CYREG_GPIO_PRT1_PC
#define EZI2C_scl__PC2 CYREG_GPIO_PRT1_PC2
#define EZI2C_scl__PORT 1u
#define EZI2C_scl__PS CYREG_GPIO_PRT1_PS
#define EZI2C_scl__SHIFT 0u

/* EZI2C_sda */
#define EZI2C_sda__0__DR CYREG_GPIO_PRT1_DR
#define EZI2C_sda__0__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define EZI2C_sda__0__DR_INV CYREG_GPIO_PRT1_DR_INV
#define EZI2C_sda__0__DR_SET CYREG_GPIO_PRT1_DR_SET
#define EZI2C_sda__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define EZI2C_sda__0__HSIOM_GPIO 0u
#define EZI2C_sda__0__HSIOM_I2C 14u
#define EZI2C_sda__0__HSIOM_I2C_SDA 14u
#define EZI2C_sda__0__HSIOM_MASK 0x000000F0u
#define EZI2C_sda__0__HSIOM_SHIFT 4u
#define EZI2C_sda__0__HSIOM_SPI 15u
#define EZI2C_sda__0__HSIOM_SPI_MISO 15u
#define EZI2C_sda__0__HSIOM_UART 9u
#define EZI2C_sda__0__HSIOM_UART_TX 9u
#define EZI2C_sda__0__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define EZI2C_sda__0__INTR CYREG_GPIO_PRT1_INTR
#define EZI2C_sda__0__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define EZI2C_sda__0__INTSTAT CYREG_GPIO_PRT1_INTR
#define EZI2C_sda__0__MASK 0x02u
#define EZI2C_sda__0__PC CYREG_GPIO_PRT1_PC
#define EZI2C_sda__0__PC2 CYREG_GPIO_PRT1_PC2
#define EZI2C_sda__0__PORT 1u
#define EZI2C_sda__0__PS CYREG_GPIO_PRT1_PS
#define EZI2C_sda__0__SHIFT 1u
#define EZI2C_sda__DR CYREG_GPIO_PRT1_DR
#define EZI2C_sda__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define EZI2C_sda__DR_INV CYREG_GPIO_PRT1_DR_INV
#define EZI2C_sda__DR_SET CYREG_GPIO_PRT1_DR_SET
#define EZI2C_sda__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define EZI2C_sda__INTR CYREG_GPIO_PRT1_INTR
#define EZI2C_sda__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define EZI2C_sda__INTSTAT CYREG_GPIO_PRT1_INTR
#define EZI2C_sda__MASK 0x02u
#define EZI2C_sda__PC CYREG_GPIO_PRT1_PC
#define EZI2C_sda__PC2 CYREG_GPIO_PRT1_PC2
#define EZI2C_sda__PORT 1u
#define EZI2C_sda__PS CYREG_GPIO_PRT1_PS
#define EZI2C_sda__SHIFT 1u

/* led_0 */
#define led_0__0__DR CYREG_GPIO_PRT3_DR
#define led_0__0__DR_CLR CYREG_GPIO_PRT3_DR_CLR
#define led_0__0__DR_INV CYREG_GPIO_PRT3_DR_INV
#define led_0__0__DR_SET CYREG_GPIO_PRT3_DR_SET
#define led_0__0__HSIOM CYREG_HSIOM_PORT_SEL3
#define led_0__0__HSIOM_MASK 0x000F0000u
#define led_0__0__HSIOM_SHIFT 16u
#define led_0__0__INTCFG CYREG_GPIO_PRT3_INTR_CFG
#define led_0__0__INTR CYREG_GPIO_PRT3_INTR
#define led_0__0__INTR_CFG CYREG_GPIO_PRT3_INTR_CFG
#define led_0__0__INTSTAT CYREG_GPIO_PRT3_INTR
#define led_0__0__MASK 0x10u
#define led_0__0__PC CYREG_GPIO_PRT3_PC
#define led_0__0__PC2 CYREG_GPIO_PRT3_PC2
#define led_0__0__PORT 3u
#define led_0__0__PS CYREG_GPIO_PRT3_PS
#define led_0__0__SHIFT 4u
#define led_0__DR CYREG_GPIO_PRT3_DR
#define led_0__DR_CLR CYREG_GPIO_PRT3_DR_CLR
#define led_0__DR_INV CYREG_GPIO_PRT3_DR_INV
#define led_0__DR_SET CYREG_GPIO_PRT3_DR_SET
#define led_0__INTCFG CYREG_GPIO_PRT3_INTR_CFG
#define led_0__INTR CYREG_GPIO_PRT3_INTR
#define led_0__INTR_CFG CYREG_GPIO_PRT3_INTR_CFG
#define led_0__INTSTAT CYREG_GPIO_PRT3_INTR
#define led_0__MASK 0x10u
#define led_0__PC CYREG_GPIO_PRT3_PC
#define led_0__PC2 CYREG_GPIO_PRT3_PC2
#define led_0__PORT 3u
#define led_0__PS CYREG_GPIO_PRT3_PS
#define led_0__SHIFT 4u

/* led_1 */
#define led_1__0__DR CYREG_GPIO_PRT3_DR
#define led_1__0__DR_CLR CYREG_GPIO_PRT3_DR_CLR
#define led_1__0__DR_INV CYREG_GPIO_PRT3_DR_INV
#define led_1__0__DR_SET CYREG_GPIO_PRT3_DR_SET
#define led_1__0__HSIOM CYREG_HSIOM_PORT_SEL3
#define led_1__0__HSIOM_MASK 0x00F00000u
#define led_1__0__HSIOM_SHIFT 20u
#define led_1__0__INTCFG CYREG_GPIO_PRT3_INTR_CFG
#define led_1__0__INTR CYREG_GPIO_PRT3_INTR
#define led_1__0__INTR_CFG CYREG_GPIO_PRT3_INTR_CFG
#define led_1__0__INTSTAT CYREG_GPIO_PRT3_INTR
#define led_1__0__MASK 0x20u
#define led_1__0__PC CYREG_GPIO_PRT3_PC
#define led_1__0__PC2 CYREG_GPIO_PRT3_PC2
#define led_1__0__PORT 3u
#define led_1__0__PS CYREG_GPIO_PRT3_PS
#define led_1__0__SHIFT 5u
#define led_1__DR CYREG_GPIO_PRT3_DR
#define led_1__DR_CLR CYREG_GPIO_PRT3_DR_CLR
#define led_1__DR_INV CYREG_GPIO_PRT3_DR_INV
#define led_1__DR_SET CYREG_GPIO_PRT3_DR_SET
#define led_1__INTCFG CYREG_GPIO_PRT3_INTR_CFG
#define led_1__INTR CYREG_GPIO_PRT3_INTR
#define led_1__INTR_CFG CYREG_GPIO_PRT3_INTR_CFG
#define led_1__INTSTAT CYREG_GPIO_PRT3_INTR
#define led_1__MASK 0x20u
#define led_1__PC CYREG_GPIO_PRT3_PC
#define led_1__PC2 CYREG_GPIO_PRT3_PC2
#define led_1__PORT 3u
#define led_1__PS CYREG_GPIO_PRT3_PS
#define led_1__SHIFT 5u

/* led_2 */
#define led_2__0__DR CYREG_GPIO_PRT3_DR
#define led_2__0__DR_CLR CYREG_GPIO_PRT3_DR_CLR
#define led_2__0__DR_INV CYREG_GPIO_PRT3_DR_INV
#define led_2__0__DR_SET CYREG_GPIO_PRT3_DR_SET
#define led_2__0__HSIOM CYREG_HSIOM_PORT_SEL3
#define led_2__0__HSIOM_MASK 0x0F000000u
#define led_2__0__HSIOM_SHIFT 24u
#define led_2__0__INTCFG CYREG_GPIO_PRT3_INTR_CFG
#define led_2__0__INTR CYREG_GPIO_PRT3_INTR
#define led_2__0__INTR_CFG CYREG_GPIO_PRT3_INTR_CFG
#define led_2__0__INTSTAT CYREG_GPIO_PRT3_INTR
#define led_2__0__MASK 0x40u
#define led_2__0__PC CYREG_GPIO_PRT3_PC
#define led_2__0__PC2 CYREG_GPIO_PRT3_PC2
#define led_2__0__PORT 3u
#define led_2__0__PS CYREG_GPIO_PRT3_PS
#define led_2__0__SHIFT 6u
#define led_2__DR CYREG_GPIO_PRT3_DR
#define led_2__DR_CLR CYREG_GPIO_PRT3_DR_CLR
#define led_2__DR_INV CYREG_GPIO_PRT3_DR_INV
#define led_2__DR_SET CYREG_GPIO_PRT3_DR_SET
#define led_2__INTCFG CYREG_GPIO_PRT3_INTR_CFG
#define led_2__INTR CYREG_GPIO_PRT3_INTR
#define led_2__INTR_CFG CYREG_GPIO_PRT3_INTR_CFG
#define led_2__INTSTAT CYREG_GPIO_PRT3_INTR
#define led_2__MASK 0x40u
#define led_2__PC CYREG_GPIO_PRT3_PC
#define led_2__PC2 CYREG_GPIO_PRT3_PC2
#define led_2__PORT 3u
#define led_2__PS CYREG_GPIO_PRT3_PS
#define led_2__SHIFT 6u

/* CapSense_CintA */
#define CapSense_CintA__0__DR CYREG_GPIO_PRT4_DR
#define CapSense_CintA__0__DR_CLR CYREG_GPIO_PRT4_DR_CLR
#define CapSense_CintA__0__DR_INV CYREG_GPIO_PRT4_DR_INV
#define CapSense_CintA__0__DR_SET CYREG_GPIO_PRT4_DR_SET
#define CapSense_CintA__0__HSIOM CYREG_HSIOM_PORT_SEL4
#define CapSense_CintA__0__HSIOM_MASK 0x00000F00u
#define CapSense_CintA__0__HSIOM_SHIFT 8u
#define CapSense_CintA__0__INTCFG CYREG_GPIO_PRT4_INTR_CFG
#define CapSense_CintA__0__INTR CYREG_GPIO_PRT4_INTR
#define CapSense_CintA__0__INTR_CFG CYREG_GPIO_PRT4_INTR_CFG
#define CapSense_CintA__0__INTSTAT CYREG_GPIO_PRT4_INTR
#define CapSense_CintA__0__MASK 0x04u
#define CapSense_CintA__0__PC CYREG_GPIO_PRT4_PC
#define CapSense_CintA__0__PC2 CYREG_GPIO_PRT4_PC2
#define CapSense_CintA__0__PORT 4u
#define CapSense_CintA__0__PS CYREG_GPIO_PRT4_PS
#define CapSense_CintA__0__SHIFT 2u
#define CapSense_CintA__DR CYREG_GPIO_PRT4_DR
#define CapSense_CintA__DR_CLR CYREG_GPIO_PRT4_DR_CLR
#define CapSense_CintA__DR_INV CYREG_GPIO_PRT4_DR_INV
#define CapSense_CintA__DR_SET CYREG_GPIO_PRT4_DR_SET
#define CapSense_CintA__INTCFG CYREG_GPIO_PRT4_INTR_CFG
#define CapSense_CintA__INTR CYREG_GPIO_PRT4_INTR
#define CapSense_CintA__INTR_CFG CYREG_GPIO_PRT4_INTR_CFG
#define CapSense_CintA__INTSTAT CYREG_GPIO_PRT4_INTR
#define CapSense_CintA__MASK 0x04u
#define CapSense_CintA__PC CYREG_GPIO_PRT4_PC
#define CapSense_CintA__PC2 CYREG_GPIO_PRT4_PC2
#define CapSense_CintA__PORT 4u
#define CapSense_CintA__PS CYREG_GPIO_PRT4_PS
#define CapSense_CintA__SHIFT 2u

/* CapSense_CintB */
#define CapSense_CintB__0__DR CYREG_GPIO_PRT4_DR
#define CapSense_CintB__0__DR_CLR CYREG_GPIO_PRT4_DR_CLR
#define CapSense_CintB__0__DR_INV CYREG_GPIO_PRT4_DR_INV
#define CapSense_CintB__0__DR_SET CYREG_GPIO_PRT4_DR_SET
#define CapSense_CintB__0__HSIOM CYREG_HSIOM_PORT_SEL4
#define CapSense_CintB__0__HSIOM_MASK 0x0000F000u
#define CapSense_CintB__0__HSIOM_SHIFT 12u
#define CapSense_CintB__0__INTCFG CYREG_GPIO_PRT4_INTR_CFG
#define CapSense_CintB__0__INTR CYREG_GPIO_PRT4_INTR
#define CapSense_CintB__0__INTR_CFG CYREG_GPIO_PRT4_INTR_CFG
#define CapSense_CintB__0__INTSTAT CYREG_GPIO_PRT4_INTR
#define CapSense_CintB__0__MASK 0x08u
#define CapSense_CintB__0__PC CYREG_GPIO_PRT4_PC
#define CapSense_CintB__0__PC2 CYREG_GPIO_PRT4_PC2
#define CapSense_CintB__0__PORT 4u
#define CapSense_CintB__0__PS CYREG_GPIO_PRT4_PS
#define CapSense_CintB__0__SHIFT 3u
#define CapSense_CintB__DR CYREG_GPIO_PRT4_DR
#define CapSense_CintB__DR_CLR CYREG_GPIO_PRT4_DR_CLR
#define CapSense_CintB__DR_INV CYREG_GPIO_PRT4_DR_INV
#define CapSense_CintB__DR_SET CYREG_GPIO_PRT4_DR_SET
#define CapSense_CintB__INTCFG CYREG_GPIO_PRT4_INTR_CFG
#define CapSense_CintB__INTR CYREG_GPIO_PRT4_INTR
#define CapSense_CintB__INTR_CFG CYREG_GPIO_PRT4_INTR_CFG
#define CapSense_CintB__INTSTAT CYREG_GPIO_PRT4_INTR
#define CapSense_CintB__MASK 0x08u
#define CapSense_CintB__PC CYREG_GPIO_PRT4_PC
#define CapSense_CintB__PC2 CYREG_GPIO_PRT4_PC2
#define CapSense_CintB__PORT 4u
#define CapSense_CintB__PS CYREG_GPIO_PRT4_PS
#define CapSense_CintB__SHIFT 3u

/* CapSense_Cmod */
#define CapSense_Cmod__0__DR CYREG_GPIO_PRT4_DR
#define CapSense_Cmod__0__DR_CLR CYREG_GPIO_PRT4_DR_CLR
#define CapSense_Cmod__0__DR_INV CYREG_GPIO_PRT4_DR_INV
#define CapSense_Cmod__0__DR_SET CYREG_GPIO_PRT4_DR_SET
#define CapSense_Cmod__0__HSIOM CYREG_HSIOM_PORT_SEL4
#define CapSense_Cmod__0__HSIOM_MASK 0x000000F0u
#define CapSense_Cmod__0__HSIOM_SHIFT 4u
#define CapSense_Cmod__0__INTCFG CYREG_GPIO_PRT4_INTR_CFG
#define CapSense_Cmod__0__INTR CYREG_GPIO_PRT4_INTR
#define CapSense_Cmod__0__INTR_CFG CYREG_GPIO_PRT4_INTR_CFG
#define CapSense_Cmod__0__INTSTAT CYREG_GPIO_PRT4_INTR
#define CapSense_Cmod__0__MASK 0x02u
#define CapSense_Cmod__0__PC CYREG_GPIO_PRT4_PC
#define CapSense_Cmod__0__PC2 CYREG_GPIO_PRT4_PC2
#define CapSense_Cmod__0__PORT 4u
#define CapSense_Cmod__0__PS CYREG_GPIO_PRT4_PS
#define CapSense_Cmod__0__SHIFT 1u
#define CapSense_Cmod__Cmod__DR CYREG_GPIO_PRT4_DR
#define CapSense_Cmod__Cmod__DR_CLR CYREG_GPIO_PRT4_DR_CLR
#define CapSense_Cmod__Cmod__DR_INV CYREG_GPIO_PRT4_DR_INV
#define CapSense_Cmod__Cmod__DR_SET CYREG_GPIO_PRT4_DR_SET
#define CapSense_Cmod__Cmod__INTCFG CYREG_GPIO_PRT4_INTR_CFG
#define CapSense_Cmod__Cmod__INTR CYREG_GPIO_PRT4_INTR
#define CapSense_Cmod__Cmod__INTR_CFG CYREG_GPIO_PRT4_INTR_CFG
#define CapSense_Cmod__Cmod__INTSTAT CYREG_GPIO_PRT4_INTR
#define CapSense_Cmod__Cmod__MASK 0x02u
#define CapSense_Cmod__Cmod__PC CYREG_GPIO_PRT4_PC
#define CapSense_Cmod__Cmod__PC2 CYREG_GPIO_PRT4_PC2
#define CapSense_Cmod__Cmod__PORT 4u
#define CapSense_Cmod__Cmod__PS CYREG_GPIO_PRT4_PS
#define CapSense_Cmod__Cmod__SHIFT 1u
#define CapSense_Cmod__DR CYREG_GPIO_PRT4_DR
#define CapSense_Cmod__DR_CLR CYREG_GPIO_PRT4_DR_CLR
#define CapSense_Cmod__DR_INV CYREG_GPIO_PRT4_DR_INV
#define CapSense_Cmod__DR_SET CYREG_GPIO_PRT4_DR_SET
#define CapSense_Cmod__INTCFG CYREG_GPIO_PRT4_INTR_CFG
#define CapSense_Cmod__INTR CYREG_GPIO_PRT4_INTR
#define CapSense_Cmod__INTR_CFG CYREG_GPIO_PRT4_INTR_CFG
#define CapSense_Cmod__INTSTAT CYREG_GPIO_PRT4_INTR
#define CapSense_Cmod__MASK 0x02u
#define CapSense_Cmod__PC CYREG_GPIO_PRT4_PC
#define CapSense_Cmod__PC2 CYREG_GPIO_PRT4_PC2
#define CapSense_Cmod__PORT 4u
#define CapSense_Cmod__PS CYREG_GPIO_PRT4_PS
#define CapSense_Cmod__SHIFT 1u

/* CapSense_CSD */
#define CapSense_CSD__ADC_CTL CYREG_CSD_ADC_CTL
#define CapSense_CSD__CSD_CONFIG CYREG_CSD_CONFIG
#define CapSense_CSD__CSD_INTR CYREG_CSD_INTR
#define CapSense_CSD__CSD_INTR_SET CYREG_CSD_INTR_SET
#define CapSense_CSD__CSD_NUMBER 0u
#define CapSense_CSD__CSD_STATUS CYREG_CSD_STATUS
#define CapSense_CSD__CSDCMP CYREG_CSD_CSDCMP
#define CapSense_CSD__HSCMP CYREG_CSD_HSCMP
#define CapSense_CSD__INTR_MASK CYREG_CSD_INTR_MASK
#define CapSense_CSD__REFGEN CYREG_CSD_REFGEN
#define CapSense_CSD__RESULT_VAL1 CYREG_CSD_RESULT_VAL1
#define CapSense_CSD__RESULT_VAL2 CYREG_CSD_RESULT_VAL2
#define CapSense_CSD__SENSE_DUTY CYREG_CSD_SENSE_DUTY
#define CapSense_CSD__SENSE_PERIOD CYREG_CSD_SENSE_PERIOD
#define CapSense_CSD__SEQ_INIT_CNT CYREG_CSD_SEQ_INIT_CNT
#define CapSense_CSD__SEQ_NORM_CNT CYREG_CSD_SEQ_NORM_CNT
#define CapSense_CSD__SEQ_START CYREG_CSD_SEQ_START
#define CapSense_CSD__SEQ_TIME CYREG_CSD_SEQ_TIME
#define CapSense_CSD__SW_AMUXBUF_SEL CYREG_CSD_SW_AMUXBUF_SEL
#define CapSense_CSD__SW_BYP_SEL CYREG_CSD_SW_BYP_SEL
#define CapSense_CSD__SW_CMP_N_SEL CYREG_CSD_SW_CMP_N_SEL
#define CapSense_CSD__SW_CMP_P_SEL CYREG_CSD_SW_CMP_P_SEL
#define CapSense_CSD__SW_DSI_SEL CYREG_CSD_SW_DSI_SEL
#define CapSense_CSD__SW_FW_MOD_SEL CYREG_CSD_SW_FW_MOD_SEL
#define CapSense_CSD__SW_FW_TANK_SEL CYREG_CSD_SW_FW_TANK_SEL
#define CapSense_CSD__SW_HS_N_SEL CYREG_CSD_SW_HS_N_SEL
#define CapSense_CSD__SW_HS_P_SEL CYREG_CSD_SW_HS_P_SEL
#define CapSense_CSD__SW_REFGEN_SEL CYREG_CSD_SW_REFGEN_SEL
#define CapSense_CSD__SW_RES CYREG_CSD_SW_RES
#define CapSense_CSD__SW_SHIELD_SEL CYREG_CSD_SW_SHIELD_SEL

/* CapSense_IDACComp */
#define CapSense_IDACComp__CONFIG CYREG_CSD_CONFIG
#define CapSense_IDACComp__IDAC CYREG_CSD_IDACB
#define CapSense_IDACComp__POSITION 1u

/* CapSense_IDACMod */
#define CapSense_IDACMod__CONFIG CYREG_CSD_CONFIG
#define CapSense_IDACMod__IDAC CYREG_CSD_IDACA
#define CapSense_IDACMod__POSITION 0u

/* CapSense_ISR */
#define CapSense_ISR__INTC_CLR_EN_REG CYREG_CM0P_ICER
#define CapSense_ISR__INTC_CLR_PD_REG CYREG_CM0P_ICPR
#define CapSense_ISR__INTC_MASK 0x400u
#define CapSense_ISR__INTC_NUMBER 10u
#define CapSense_ISR__INTC_PRIOR_MASK 0xC00000u
#define CapSense_ISR__INTC_PRIOR_NUM 3u
#define CapSense_ISR__INTC_PRIOR_REG CYREG_CM0P_IPR2
#define CapSense_ISR__INTC_SET_EN_REG CYREG_CM0P_ISER
#define CapSense_ISR__INTC_SET_PD_REG CYREG_CM0P_ISPR

/* CapSense_ModClk */
#define CapSense_ModClk__CTRL_REGISTER CYREG_PERI_PCLK_CTL2
#define CapSense_ModClk__DIV_ID 0x00000040u
#define CapSense_ModClk__DIV_REGISTER CYREG_PERI_DIV_16_CTL0
#define CapSense_ModClk__PA_DIV_ID 0x000000FFu

/* CapSense_Rx */
#define CapSense_Rx__0__DR CYREG_GPIO_PRT1_DR
#define CapSense_Rx__0__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define CapSense_Rx__0__DR_INV CYREG_GPIO_PRT1_DR_INV
#define CapSense_Rx__0__DR_SET CYREG_GPIO_PRT1_DR_SET
#define CapSense_Rx__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define CapSense_Rx__0__HSIOM_MASK 0x000F0000u
#define CapSense_Rx__0__HSIOM_SHIFT 16u
#define CapSense_Rx__0__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Rx__0__INTR CYREG_GPIO_PRT1_INTR
#define CapSense_Rx__0__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Rx__0__INTSTAT CYREG_GPIO_PRT1_INTR
#define CapSense_Rx__0__MASK 0x10u
#define CapSense_Rx__0__PC CYREG_GPIO_PRT1_PC
#define CapSense_Rx__0__PC2 CYREG_GPIO_PRT1_PC2
#define CapSense_Rx__0__PORT 1u
#define CapSense_Rx__0__PS CYREG_GPIO_PRT1_PS
#define CapSense_Rx__0__SHIFT 4u
#define CapSense_Rx__1__DR CYREG_GPIO_PRT1_DR
#define CapSense_Rx__1__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define CapSense_Rx__1__DR_INV CYREG_GPIO_PRT1_DR_INV
#define CapSense_Rx__1__DR_SET CYREG_GPIO_PRT1_DR_SET
#define CapSense_Rx__1__HSIOM CYREG_HSIOM_PORT_SEL1
#define CapSense_Rx__1__HSIOM_MASK 0x00F00000u
#define CapSense_Rx__1__HSIOM_SHIFT 20u
#define CapSense_Rx__1__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Rx__1__INTR CYREG_GPIO_PRT1_INTR
#define CapSense_Rx__1__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Rx__1__INTSTAT CYREG_GPIO_PRT1_INTR
#define CapSense_Rx__1__MASK 0x20u
#define CapSense_Rx__1__PC CYREG_GPIO_PRT1_PC
#define CapSense_Rx__1__PC2 CYREG_GPIO_PRT1_PC2
#define CapSense_Rx__1__PORT 1u
#define CapSense_Rx__1__PS CYREG_GPIO_PRT1_PS
#define CapSense_Rx__1__SHIFT 5u
#define CapSense_Rx__2__DR CYREG_GPIO_PRT1_DR
#define CapSense_Rx__2__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define CapSense_Rx__2__DR_INV CYREG_GPIO_PRT1_DR_INV
#define CapSense_Rx__2__DR_SET CYREG_GPIO_PRT1_DR_SET
#define CapSense_Rx__2__HSIOM CYREG_HSIOM_PORT_SEL1
#define CapSense_Rx__2__HSIOM_MASK 0x0F000000u
#define CapSense_Rx__2__HSIOM_SHIFT 24u
#define CapSense_Rx__2__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Rx__2__INTR CYREG_GPIO_PRT1_INTR
#define CapSense_Rx__2__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Rx__2__INTSTAT CYREG_GPIO_PRT1_INTR
#define CapSense_Rx__2__MASK 0x40u
#define CapSense_Rx__2__PC CYREG_GPIO_PRT1_PC
#define CapSense_Rx__2__PC2 CYREG_GPIO_PRT1_PC2
#define CapSense_Rx__2__PORT 1u
#define CapSense_Rx__2__PS CYREG_GPIO_PRT1_PS
#define CapSense_Rx__2__SHIFT 6u
#define CapSense_Rx__Button0_Rx0__DR CYREG_GPIO_PRT1_DR
#define CapSense_Rx__Button0_Rx0__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define CapSense_Rx__Button0_Rx0__DR_INV CYREG_GPIO_PRT1_DR_INV
#define CapSense_Rx__Button0_Rx0__DR_SET CYREG_GPIO_PRT1_DR_SET
#define CapSense_Rx__Button0_Rx0__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Rx__Button0_Rx0__INTR CYREG_GPIO_PRT1_INTR
#define CapSense_Rx__Button0_Rx0__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Rx__Button0_Rx0__INTSTAT CYREG_GPIO_PRT1_INTR
#define CapSense_Rx__Button0_Rx0__MASK 0x10u
#define CapSense_Rx__Button0_Rx0__PC CYREG_GPIO_PRT1_PC
#define CapSense_Rx__Button0_Rx0__PC2 CYREG_GPIO_PRT1_PC2
#define CapSense_Rx__Button0_Rx0__PORT 1u
#define CapSense_Rx__Button0_Rx0__PS CYREG_GPIO_PRT1_PS
#define CapSense_Rx__Button0_Rx0__SHIFT 4u
#define CapSense_Rx__Button1_Rx0__DR CYREG_GPIO_PRT1_DR
#define CapSense_Rx__Button1_Rx0__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define CapSense_Rx__Button1_Rx0__DR_INV CYREG_GPIO_PRT1_DR_INV
#define CapSense_Rx__Button1_Rx0__DR_SET CYREG_GPIO_PRT1_DR_SET
#define CapSense_Rx__Button1_Rx0__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Rx__Button1_Rx0__INTR CYREG_GPIO_PRT1_INTR
#define CapSense_Rx__Button1_Rx0__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Rx__Button1_Rx0__INTSTAT CYREG_GPIO_PRT1_INTR
#define CapSense_Rx__Button1_Rx0__MASK 0x20u
#define CapSense_Rx__Button1_Rx0__PC CYREG_GPIO_PRT1_PC
#define CapSense_Rx__Button1_Rx0__PC2 CYREG_GPIO_PRT1_PC2
#define CapSense_Rx__Button1_Rx0__PORT 1u
#define CapSense_Rx__Button1_Rx0__PS CYREG_GPIO_PRT1_PS
#define CapSense_Rx__Button1_Rx0__SHIFT 5u
#define CapSense_Rx__Button2_Rx0__DR CYREG_GPIO_PRT1_DR
#define CapSense_Rx__Button2_Rx0__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define CapSense_Rx__Button2_Rx0__DR_INV CYREG_GPIO_PRT1_DR_INV
#define CapSense_Rx__Button2_Rx0__DR_SET CYREG_GPIO_PRT1_DR_SET
#define CapSense_Rx__Button2_Rx0__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Rx__Button2_Rx0__INTR CYREG_GPIO_PRT1_INTR
#define CapSense_Rx__Button2_Rx0__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Rx__Button2_Rx0__INTSTAT CYREG_GPIO_PRT1_INTR
#define CapSense_Rx__Button2_Rx0__MASK 0x40u
#define CapSense_Rx__Button2_Rx0__PC CYREG_GPIO_PRT1_PC
#define CapSense_Rx__Button2_Rx0__PC2 CYREG_GPIO_PRT1_PC2
#define CapSense_Rx__Button2_Rx0__PORT 1u
#define CapSense_Rx__Button2_Rx0__PS CYREG_GPIO_PRT1_PS
#define CapSense_Rx__Button2_Rx0__SHIFT 6u
#define CapSense_Rx__DR CYREG_GPIO_PRT1_DR
#define CapSense_Rx__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define CapSense_Rx__DR_INV CYREG_GPIO_PRT1_DR_INV
#define CapSense_Rx__DR_SET CYREG_GPIO_PRT1_DR_SET
#define CapSense_Rx__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Rx__INTR CYREG_GPIO_PRT1_INTR
#define CapSense_Rx__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Rx__INTSTAT CYREG_GPIO_PRT1_INTR
#define CapSense_Rx__PC CYREG_GPIO_PRT1_PC
#define CapSense_Rx__PC2 CYREG_GPIO_PRT1_PC2
#define CapSense_Rx__PORT 1u
#define CapSense_Rx__PS CYREG_GPIO_PRT1_PS

/* CapSense_Sns */
#define CapSense_Sns__0__DR CYREG_GPIO_PRT0_DR
#define CapSense_Sns__0__DR_CLR CYREG_GPIO_PRT0_DR_CLR
#define CapSense_Sns__0__DR_INV CYREG_GPIO_PRT0_DR_INV
#define CapSense_Sns__0__DR_SET CYREG_GPIO_PRT0_DR_SET
#define CapSense_Sns__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define CapSense_Sns__0__HSIOM_MASK 0x0F000000u
#define CapSense_Sns__0__HSIOM_SHIFT 24u
#define CapSense_Sns__0__INTCFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__0__INTR CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__0__INTR_CFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__0__INTSTAT CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__0__MASK 0x40u
#define CapSense_Sns__0__PC CYREG_GPIO_PRT0_PC
#define CapSense_Sns__0__PC2 CYREG_GPIO_PRT0_PC2
#define CapSense_Sns__0__PORT 0u
#define CapSense_Sns__0__PS CYREG_GPIO_PRT0_PS
#define CapSense_Sns__0__SHIFT 6u
#define CapSense_Sns__1__DR CYREG_GPIO_PRT0_DR
#define CapSense_Sns__1__DR_CLR CYREG_GPIO_PRT0_DR_CLR
#define CapSense_Sns__1__DR_INV CYREG_GPIO_PRT0_DR_INV
#define CapSense_Sns__1__DR_SET CYREG_GPIO_PRT0_DR_SET
#define CapSense_Sns__1__HSIOM CYREG_HSIOM_PORT_SEL0
#define CapSense_Sns__1__HSIOM_MASK 0x0000F000u
#define CapSense_Sns__1__HSIOM_SHIFT 12u
#define CapSense_Sns__1__INTCFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__1__INTR CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__1__INTR_CFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__1__INTSTAT CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__1__MASK 0x08u
#define CapSense_Sns__1__PC CYREG_GPIO_PRT0_PC
#define CapSense_Sns__1__PC2 CYREG_GPIO_PRT0_PC2
#define CapSense_Sns__1__PORT 0u
#define CapSense_Sns__1__PS CYREG_GPIO_PRT0_PS
#define CapSense_Sns__1__SHIFT 3u
#define CapSense_Sns__2__DR CYREG_GPIO_PRT0_DR
#define CapSense_Sns__2__DR_CLR CYREG_GPIO_PRT0_DR_CLR
#define CapSense_Sns__2__DR_INV CYREG_GPIO_PRT0_DR_INV
#define CapSense_Sns__2__DR_SET CYREG_GPIO_PRT0_DR_SET
#define CapSense_Sns__2__HSIOM CYREG_HSIOM_PORT_SEL0
#define CapSense_Sns__2__HSIOM_MASK 0x00000F00u
#define CapSense_Sns__2__HSIOM_SHIFT 8u
#define CapSense_Sns__2__INTCFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__2__INTR CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__2__INTR_CFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__2__INTSTAT CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__2__MASK 0x04u
#define CapSense_Sns__2__PC CYREG_GPIO_PRT0_PC
#define CapSense_Sns__2__PC2 CYREG_GPIO_PRT0_PC2
#define CapSense_Sns__2__PORT 0u
#define CapSense_Sns__2__PS CYREG_GPIO_PRT0_PS
#define CapSense_Sns__2__SHIFT 2u
#define CapSense_Sns__3__DR CYREG_GPIO_PRT0_DR
#define CapSense_Sns__3__DR_CLR CYREG_GPIO_PRT0_DR_CLR
#define CapSense_Sns__3__DR_INV CYREG_GPIO_PRT0_DR_INV
#define CapSense_Sns__3__DR_SET CYREG_GPIO_PRT0_DR_SET
#define CapSense_Sns__3__HSIOM CYREG_HSIOM_PORT_SEL0
#define CapSense_Sns__3__HSIOM_MASK 0x000000F0u
#define CapSense_Sns__3__HSIOM_SHIFT 4u
#define CapSense_Sns__3__INTCFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__3__INTR CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__3__INTR_CFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__3__INTSTAT CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__3__MASK 0x02u
#define CapSense_Sns__3__PC CYREG_GPIO_PRT0_PC
#define CapSense_Sns__3__PC2 CYREG_GPIO_PRT0_PC2
#define CapSense_Sns__3__PORT 0u
#define CapSense_Sns__3__PS CYREG_GPIO_PRT0_PS
#define CapSense_Sns__3__SHIFT 1u
#define CapSense_Sns__4__DR CYREG_GPIO_PRT0_DR
#define CapSense_Sns__4__DR_CLR CYREG_GPIO_PRT0_DR_CLR
#define CapSense_Sns__4__DR_INV CYREG_GPIO_PRT0_DR_INV
#define CapSense_Sns__4__DR_SET CYREG_GPIO_PRT0_DR_SET
#define CapSense_Sns__4__HSIOM CYREG_HSIOM_PORT_SEL0
#define CapSense_Sns__4__HSIOM_MASK 0x0000000Fu
#define CapSense_Sns__4__HSIOM_SHIFT 0u
#define CapSense_Sns__4__INTCFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__4__INTR CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__4__INTR_CFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__4__INTSTAT CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__4__MASK 0x01u
#define CapSense_Sns__4__PC CYREG_GPIO_PRT0_PC
#define CapSense_Sns__4__PC2 CYREG_GPIO_PRT0_PC2
#define CapSense_Sns__4__PORT 0u
#define CapSense_Sns__4__PS CYREG_GPIO_PRT0_PS
#define CapSense_Sns__4__SHIFT 0u
#define CapSense_Sns__DR CYREG_GPIO_PRT0_DR
#define CapSense_Sns__DR_CLR CYREG_GPIO_PRT0_DR_CLR
#define CapSense_Sns__DR_INV CYREG_GPIO_PRT0_DR_INV
#define CapSense_Sns__DR_SET CYREG_GPIO_PRT0_DR_SET
#define CapSense_Sns__INTCFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__INTR CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__INTR_CFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__INTSTAT CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__LinearSlider0_Sns0__DR CYREG_GPIO_PRT0_DR
#define CapSense_Sns__LinearSlider0_Sns0__DR_CLR CYREG_GPIO_PRT0_DR_CLR
#define CapSense_Sns__LinearSlider0_Sns0__DR_INV CYREG_GPIO_PRT0_DR_INV
#define CapSense_Sns__LinearSlider0_Sns0__DR_SET CYREG_GPIO_PRT0_DR_SET
#define CapSense_Sns__LinearSlider0_Sns0__INTCFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__LinearSlider0_Sns0__INTR CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__LinearSlider0_Sns0__INTR_CFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__LinearSlider0_Sns0__INTSTAT CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__LinearSlider0_Sns0__MASK 0x40u
#define CapSense_Sns__LinearSlider0_Sns0__PC CYREG_GPIO_PRT0_PC
#define CapSense_Sns__LinearSlider0_Sns0__PC2 CYREG_GPIO_PRT0_PC2
#define CapSense_Sns__LinearSlider0_Sns0__PORT 0u
#define CapSense_Sns__LinearSlider0_Sns0__PS CYREG_GPIO_PRT0_PS
#define CapSense_Sns__LinearSlider0_Sns0__SHIFT 6u
#define CapSense_Sns__LinearSlider0_Sns1__DR CYREG_GPIO_PRT0_DR
#define CapSense_Sns__LinearSlider0_Sns1__DR_CLR CYREG_GPIO_PRT0_DR_CLR
#define CapSense_Sns__LinearSlider0_Sns1__DR_INV CYREG_GPIO_PRT0_DR_INV
#define CapSense_Sns__LinearSlider0_Sns1__DR_SET CYREG_GPIO_PRT0_DR_SET
#define CapSense_Sns__LinearSlider0_Sns1__INTCFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__LinearSlider0_Sns1__INTR CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__LinearSlider0_Sns1__INTR_CFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__LinearSlider0_Sns1__INTSTAT CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__LinearSlider0_Sns1__MASK 0x08u
#define CapSense_Sns__LinearSlider0_Sns1__PC CYREG_GPIO_PRT0_PC
#define CapSense_Sns__LinearSlider0_Sns1__PC2 CYREG_GPIO_PRT0_PC2
#define CapSense_Sns__LinearSlider0_Sns1__PORT 0u
#define CapSense_Sns__LinearSlider0_Sns1__PS CYREG_GPIO_PRT0_PS
#define CapSense_Sns__LinearSlider0_Sns1__SHIFT 3u
#define CapSense_Sns__LinearSlider0_Sns2__DR CYREG_GPIO_PRT0_DR
#define CapSense_Sns__LinearSlider0_Sns2__DR_CLR CYREG_GPIO_PRT0_DR_CLR
#define CapSense_Sns__LinearSlider0_Sns2__DR_INV CYREG_GPIO_PRT0_DR_INV
#define CapSense_Sns__LinearSlider0_Sns2__DR_SET CYREG_GPIO_PRT0_DR_SET
#define CapSense_Sns__LinearSlider0_Sns2__INTCFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__LinearSlider0_Sns2__INTR CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__LinearSlider0_Sns2__INTR_CFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__LinearSlider0_Sns2__INTSTAT CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__LinearSlider0_Sns2__MASK 0x04u
#define CapSense_Sns__LinearSlider0_Sns2__PC CYREG_GPIO_PRT0_PC
#define CapSense_Sns__LinearSlider0_Sns2__PC2 CYREG_GPIO_PRT0_PC2
#define CapSense_Sns__LinearSlider0_Sns2__PORT 0u
#define CapSense_Sns__LinearSlider0_Sns2__PS CYREG_GPIO_PRT0_PS
#define CapSense_Sns__LinearSlider0_Sns2__SHIFT 2u
#define CapSense_Sns__LinearSlider0_Sns3__DR CYREG_GPIO_PRT0_DR
#define CapSense_Sns__LinearSlider0_Sns3__DR_CLR CYREG_GPIO_PRT0_DR_CLR
#define CapSense_Sns__LinearSlider0_Sns3__DR_INV CYREG_GPIO_PRT0_DR_INV
#define CapSense_Sns__LinearSlider0_Sns3__DR_SET CYREG_GPIO_PRT0_DR_SET
#define CapSense_Sns__LinearSlider0_Sns3__INTCFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__LinearSlider0_Sns3__INTR CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__LinearSlider0_Sns3__INTR_CFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__LinearSlider0_Sns3__INTSTAT CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__LinearSlider0_Sns3__MASK 0x02u
#define CapSense_Sns__LinearSlider0_Sns3__PC CYREG_GPIO_PRT0_PC
#define CapSense_Sns__LinearSlider0_Sns3__PC2 CYREG_GPIO_PRT0_PC2
#define CapSense_Sns__LinearSlider0_Sns3__PORT 0u
#define CapSense_Sns__LinearSlider0_Sns3__PS CYREG_GPIO_PRT0_PS
#define CapSense_Sns__LinearSlider0_Sns3__SHIFT 1u
#define CapSense_Sns__LinearSlider0_Sns4__DR CYREG_GPIO_PRT0_DR
#define CapSense_Sns__LinearSlider0_Sns4__DR_CLR CYREG_GPIO_PRT0_DR_CLR
#define CapSense_Sns__LinearSlider0_Sns4__DR_INV CYREG_GPIO_PRT0_DR_INV
#define CapSense_Sns__LinearSlider0_Sns4__DR_SET CYREG_GPIO_PRT0_DR_SET
#define CapSense_Sns__LinearSlider0_Sns4__INTCFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__LinearSlider0_Sns4__INTR CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__LinearSlider0_Sns4__INTR_CFG CYREG_GPIO_PRT0_INTR_CFG
#define CapSense_Sns__LinearSlider0_Sns4__INTSTAT CYREG_GPIO_PRT0_INTR
#define CapSense_Sns__LinearSlider0_Sns4__MASK 0x01u
#define CapSense_Sns__LinearSlider0_Sns4__PC CYREG_GPIO_PRT0_PC
#define CapSense_Sns__LinearSlider0_Sns4__PC2 CYREG_GPIO_PRT0_PC2
#define CapSense_Sns__LinearSlider0_Sns4__PORT 0u
#define CapSense_Sns__LinearSlider0_Sns4__PS CYREG_GPIO_PRT0_PS
#define CapSense_Sns__LinearSlider0_Sns4__SHIFT 0u
#define CapSense_Sns__PC CYREG_GPIO_PRT0_PC
#define CapSense_Sns__PC2 CYREG_GPIO_PRT0_PC2
#define CapSense_Sns__PORT 0u
#define CapSense_Sns__PS CYREG_GPIO_PRT0_PS

/* CapSense_Tx */
#define CapSense_Tx__0__DR CYREG_GPIO_PRT1_DR
#define CapSense_Tx__0__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define CapSense_Tx__0__DR_INV CYREG_GPIO_PRT1_DR_INV
#define CapSense_Tx__0__DR_SET CYREG_GPIO_PRT1_DR_SET
#define CapSense_Tx__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define CapSense_Tx__0__HSIOM_MASK 0x0000F000u
#define CapSense_Tx__0__HSIOM_SHIFT 12u
#define CapSense_Tx__0__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Tx__0__INTR CYREG_GPIO_PRT1_INTR
#define CapSense_Tx__0__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Tx__0__INTSTAT CYREG_GPIO_PRT1_INTR
#define CapSense_Tx__0__MASK 0x08u
#define CapSense_Tx__0__PC CYREG_GPIO_PRT1_PC
#define CapSense_Tx__0__PC2 CYREG_GPIO_PRT1_PC2
#define CapSense_Tx__0__PORT 1u
#define CapSense_Tx__0__PS CYREG_GPIO_PRT1_PS
#define CapSense_Tx__0__SHIFT 3u
#define CapSense_Tx__Button0_Tx__DR CYREG_GPIO_PRT1_DR
#define CapSense_Tx__Button0_Tx__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define CapSense_Tx__Button0_Tx__DR_INV CYREG_GPIO_PRT1_DR_INV
#define CapSense_Tx__Button0_Tx__DR_SET CYREG_GPIO_PRT1_DR_SET
#define CapSense_Tx__Button0_Tx__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Tx__Button0_Tx__INTR CYREG_GPIO_PRT1_INTR
#define CapSense_Tx__Button0_Tx__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Tx__Button0_Tx__INTSTAT CYREG_GPIO_PRT1_INTR
#define CapSense_Tx__Button0_Tx__MASK 0x08u
#define CapSense_Tx__Button0_Tx__PC CYREG_GPIO_PRT1_PC
#define CapSense_Tx__Button0_Tx__PC2 CYREG_GPIO_PRT1_PC2
#define CapSense_Tx__Button0_Tx__PORT 1u
#define CapSense_Tx__Button0_Tx__PS CYREG_GPIO_PRT1_PS
#define CapSense_Tx__Button0_Tx__SHIFT 3u
#define CapSense_Tx__DR CYREG_GPIO_PRT1_DR
#define CapSense_Tx__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define CapSense_Tx__DR_INV CYREG_GPIO_PRT1_DR_INV
#define CapSense_Tx__DR_SET CYREG_GPIO_PRT1_DR_SET
#define CapSense_Tx__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Tx__INTR CYREG_GPIO_PRT1_INTR
#define CapSense_Tx__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define CapSense_Tx__INTSTAT CYREG_GPIO_PRT1_INTR
#define CapSense_Tx__MASK 0x08u
#define CapSense_Tx__PC CYREG_GPIO_PRT1_PC
#define CapSense_Tx__PC2 CYREG_GPIO_PRT1_PC2
#define CapSense_Tx__PORT 1u
#define CapSense_Tx__PS CYREG_GPIO_PRT1_PS
#define CapSense_Tx__SHIFT 3u

/* Miscellaneous */
#define CY_PROJECT_NAME "TestI2C-145"
#define CY_VERSION "PSoC Creator  3.3 CP3"
#define CYDEV_BANDGAP_VOLTAGE 1.200
#define CYDEV_BCLK__HFCLK__HZ 24000000U
#define CYDEV_BCLK__HFCLK__KHZ 24000U
#define CYDEV_BCLK__HFCLK__MHZ 24U
#define CYDEV_BCLK__SYSCLK__HZ 24000000U
#define CYDEV_BCLK__SYSCLK__KHZ 24000U
#define CYDEV_BCLK__SYSCLK__MHZ 24U
#define CYDEV_CHIP_DIE_LEOPARD 1u
#define CYDEV_CHIP_DIE_PANTHER 19u
#define CYDEV_CHIP_DIE_PSOC4A 11u
#define CYDEV_CHIP_DIE_PSOC5LP 18u
#define CYDEV_CHIP_DIE_TMA4 2u
#define CYDEV_CHIP_DIE_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_PSOC3 1u
#define CYDEV_CHIP_FAMILY_PSOC4 2u
#define CYDEV_CHIP_FAMILY_PSOC5 3u
#define CYDEV_CHIP_FAMILY_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_USED CYDEV_CHIP_FAMILY_PSOC4
#define CYDEV_CHIP_JTAG_ID 0x190111A9u
#define CYDEV_CHIP_MEMBER_3A 1u
#define CYDEV_CHIP_MEMBER_4A 11u
#define CYDEV_CHIP_MEMBER_4C 16u
#define CYDEV_CHIP_MEMBER_4D 7u
#define CYDEV_CHIP_MEMBER_4E 4u
#define CYDEV_CHIP_MEMBER_4F 12u
#define CYDEV_CHIP_MEMBER_4G 2u
#define CYDEV_CHIP_MEMBER_4H 10u
#define CYDEV_CHIP_MEMBER_4I 15u
#define CYDEV_CHIP_MEMBER_4J 8u
#define CYDEV_CHIP_MEMBER_4K 9u
#define CYDEV_CHIP_MEMBER_4L 14u
#define CYDEV_CHIP_MEMBER_4M 13u
#define CYDEV_CHIP_MEMBER_4N 6u
#define CYDEV_CHIP_MEMBER_4O 5u
#define CYDEV_CHIP_MEMBER_4U 3u
#define CYDEV_CHIP_MEMBER_5A 18u
#define CYDEV_CHIP_MEMBER_5B 17u
#define CYDEV_CHIP_MEMBER_UNKNOWN 0u
#define CYDEV_CHIP_MEMBER_USED CYDEV_CHIP_MEMBER_4J
#define CYDEV_CHIP_DIE_EXPECT CYDEV_CHIP_MEMBER_USED
#define CYDEV_CHIP_DIE_ACTUAL CYDEV_CHIP_DIE_EXPECT
#define CYDEV_CHIP_REV_LEOPARD_ES1 0u
#define CYDEV_CHIP_REV_LEOPARD_ES2 1u
#define CYDEV_CHIP_REV_LEOPARD_ES3 3u
#define CYDEV_CHIP_REV_LEOPARD_PRODUCTION 3u
#define CYDEV_CHIP_REV_PANTHER_ES0 0u
#define CYDEV_CHIP_REV_PANTHER_ES1 1u
#define CYDEV_CHIP_REV_PANTHER_PRODUCTION 1u
#define CYDEV_CHIP_REV_PSOC4A_ES0 17u
#define CYDEV_CHIP_REV_PSOC4A_PRODUCTION 17u
#define CYDEV_CHIP_REV_PSOC5LP_ES0 0u
#define CYDEV_CHIP_REV_PSOC5LP_PRODUCTION 0u
#define CYDEV_CHIP_REV_TMA4_ES 17u
#define CYDEV_CHIP_REV_TMA4_ES2 33u
#define CYDEV_CHIP_REV_TMA4_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_3A_ES1 0u
#define CYDEV_CHIP_REVISION_3A_ES2 1u
#define CYDEV_CHIP_REVISION_3A_ES3 3u
#define CYDEV_CHIP_REVISION_3A_PRODUCTION 3u
#define CYDEV_CHIP_REVISION_4A_ES0 17u
#define CYDEV_CHIP_REVISION_4A_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4C_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4D_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4E_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION_256DMA 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION_256K 0u
#define CYDEV_CHIP_REVISION_4G_ES 17u
#define CYDEV_CHIP_REVISION_4G_ES2 33u
#define CYDEV_CHIP_REVISION_4G_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4H_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4I_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4J_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4K_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4L_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4M_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4N_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4O_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4U_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_5A_ES0 0u
#define CYDEV_CHIP_REVISION_5A_ES1 1u
#define CYDEV_CHIP_REVISION_5A_PRODUCTION 1u
#define CYDEV_CHIP_REVISION_5B_ES0 0u
#define CYDEV_CHIP_REVISION_5B_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_USED CYDEV_CHIP_REVISION_4J_PRODUCTION
#define CYDEV_CHIP_REV_EXPECT CYDEV_CHIP_REVISION_USED
#define CYDEV_CONFIG_READ_ACCELERATOR 1
#define CYDEV_CONFIG_UNUSED_IO_AllowButWarn 0
#define CYDEV_CONFIG_UNUSED_IO CYDEV_CONFIG_UNUSED_IO_AllowButWarn
#define CYDEV_CONFIG_UNUSED_IO_AllowWithInfo 1
#define CYDEV_CONFIG_UNUSED_IO_Disallowed 2
#define CYDEV_CONFIGURATION_COMPRESSED 1
#define CYDEV_CONFIGURATION_MODE_COMPRESSED 0
#define CYDEV_CONFIGURATION_MODE CYDEV_CONFIGURATION_MODE_COMPRESSED
#define CYDEV_CONFIGURATION_MODE_DMA 2
#define CYDEV_CONFIGURATION_MODE_UNCOMPRESSED 1
#define CYDEV_DEBUG_PROTECT_KILL 4
#define CYDEV_DEBUG_PROTECT_OPEN 1
#define CYDEV_DEBUG_PROTECT CYDEV_DEBUG_PROTECT_OPEN
#define CYDEV_DEBUG_PROTECT_PROTECTED 2
#define CYDEV_DEBUGGING_DPS_Disable 3
#define CYDEV_DEBUGGING_DPS_SWD 2
#define CYDEV_DEBUGGING_DPS CYDEV_DEBUGGING_DPS_SWD
#define CYDEV_DEBUGGING_ENABLE 1
#define CYDEV_DFT_SELECT_CLK0 8u
#define CYDEV_DFT_SELECT_CLK1 9u
#define CYDEV_HEAP_SIZE 0x80
#define CYDEV_IMO_TRIMMED_BY_USB 0u
#define CYDEV_IMO_TRIMMED_BY_WCO 0u
#define CYDEV_IS_EXPORTING_CODE 0
#define CYDEV_IS_IMPORTING_CODE 0
#define CYDEV_PROJ_TYPE 0
#define CYDEV_PROJ_TYPE_BOOTLOADER 1
#define CYDEV_PROJ_TYPE_LAUNCHER 5
#define CYDEV_PROJ_TYPE_LOADABLE 2
#define CYDEV_PROJ_TYPE_LOADABLEANDBOOTLOADER 4
#define CYDEV_PROJ_TYPE_MULTIAPPBOOTLOADER 3
#define CYDEV_PROJ_TYPE_STANDARD 0
#define CYDEV_STACK_SIZE 0x0400
#define CYDEV_USE_BUNDLED_CMSIS 1
#define CYDEV_VARIABLE_VDDA 1
#define CYDEV_VDDA 3.3
#define CYDEV_VDDA_MV 3300
#define CYDEV_VDDD 3.3
#define CYDEV_VDDD_MV 3300
#define CYDEV_WDT_GENERATE_ISR 0u
#define CYIPBLOCK_m0s8cpussv3_VERSION 1
#define CYIPBLOCK_m0s8csdv2_VERSION 1
#define CYIPBLOCK_m0s8ioss_VERSION 1
#define CYIPBLOCK_m0s8lcd_VERSION 2
#define CYIPBLOCK_m0s8lpcomp_VERSION 2
#define CYIPBLOCK_m0s8peri_VERSION 1
#define CYIPBLOCK_m0s8scb_VERSION 2
#define CYIPBLOCK_m0s8tcpwm_VERSION 2
#define CYIPBLOCK_m0s8wco_VERSION 1
#define CYIPBLOCK_s8srsslt_VERSION 1
#define CYDEV_BOOTLOADER_ENABLE 0

#endif /* INCLUDED_CYFITTER_H */
